//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderingBuddy.NotifyMeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/NotifyMeService.Wcf.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FoodOrderingBuddy.NotifyMeService.SmsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FoodOrderingBuddy.NotifyMeService.EmailRequest))]
    public partial class BaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsRequest", Namespace="http://schemas.datacontract.org/2004/07/NotifyMeService.Wcf.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SmsRequest : FoodOrderingBuddy.NotifyMeService.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailRequest", Namespace="http://schemas.datacontract.org/2004/07/NotifyMeService.Wcf.DataContracts")]
    [System.SerializableAttribute()]
    public partial class EmailRequest : FoodOrderingBuddy.NotifyMeService.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/NotifyMeService.Wcf.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FoodOrderingBuddy.NotifyMeService.SmsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FoodOrderingBuddy.NotifyMeService.EmailResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SubmittedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SubmittedDateTime {
            get {
                return this.SubmittedDateTimeField;
            }
            set {
                if ((this.SubmittedDateTimeField.Equals(value) != true)) {
                    this.SubmittedDateTimeField = value;
                    this.RaisePropertyChanged("SubmittedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsResponse", Namespace="http://schemas.datacontract.org/2004/07/NotifyMeService.Wcf.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SmsResponse : FoodOrderingBuddy.NotifyMeService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApiMessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApiMessageId {
            get {
                return this.ApiMessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ApiMessageIdField, value) != true)) {
                    this.ApiMessageIdField = value;
                    this.RaisePropertyChanged("ApiMessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextMessage {
            get {
                return this.TextMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.TextMessageField, value) != true)) {
                    this.TextMessageField = value;
                    this.RaisePropertyChanged("TextMessage");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailResponse", Namespace="http://schemas.datacontract.org/2004/07/NotifyMeService.Wcf.DataContracts")]
    [System.SerializableAttribute()]
    public partial class EmailResponse : FoodOrderingBuddy.NotifyMeService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotifyMeService.INotifyMeService")]
    public interface INotifyMeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifyMeService/NotifymeThankyoubyEmail", ReplyAction="http://tempuri.org/INotifyMeService/NotifymeThankyoubyEmailResponse")]
        FoodOrderingBuddy.NotifyMeService.EmailResponse NotifymeThankyoubyEmail(FoodOrderingBuddy.NotifyMeService.EmailRequest emailRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifyMeService/NotifymeThankyoubyEmail", ReplyAction="http://tempuri.org/INotifyMeService/NotifymeThankyoubyEmailResponse")]
        System.Threading.Tasks.Task<FoodOrderingBuddy.NotifyMeService.EmailResponse> NotifymeThankyoubyEmailAsync(FoodOrderingBuddy.NotifyMeService.EmailRequest emailRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifyMeService/PingmePleasebySms", ReplyAction="http://tempuri.org/INotifyMeService/PingmePleasebySmsResponse")]
        FoodOrderingBuddy.NotifyMeService.SmsResponse PingmePleasebySms(FoodOrderingBuddy.NotifyMeService.SmsRequest smsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifyMeService/PingmePleasebySms", ReplyAction="http://tempuri.org/INotifyMeService/PingmePleasebySmsResponse")]
        System.Threading.Tasks.Task<FoodOrderingBuddy.NotifyMeService.SmsResponse> PingmePleasebySmsAsync(FoodOrderingBuddy.NotifyMeService.SmsRequest smsRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotifyMeServiceChannel : FoodOrderingBuddy.NotifyMeService.INotifyMeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotifyMeServiceClient : System.ServiceModel.ClientBase<FoodOrderingBuddy.NotifyMeService.INotifyMeService>, FoodOrderingBuddy.NotifyMeService.INotifyMeService {
        
        public NotifyMeServiceClient() {
        }
        
        public NotifyMeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotifyMeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotifyMeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotifyMeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FoodOrderingBuddy.NotifyMeService.EmailResponse NotifymeThankyoubyEmail(FoodOrderingBuddy.NotifyMeService.EmailRequest emailRequest) {
            return base.Channel.NotifymeThankyoubyEmail(emailRequest);
        }
        
        public System.Threading.Tasks.Task<FoodOrderingBuddy.NotifyMeService.EmailResponse> NotifymeThankyoubyEmailAsync(FoodOrderingBuddy.NotifyMeService.EmailRequest emailRequest) {
            return base.Channel.NotifymeThankyoubyEmailAsync(emailRequest);
        }
        
        public FoodOrderingBuddy.NotifyMeService.SmsResponse PingmePleasebySms(FoodOrderingBuddy.NotifyMeService.SmsRequest smsRequest) {
            return base.Channel.PingmePleasebySms(smsRequest);
        }
        
        public System.Threading.Tasks.Task<FoodOrderingBuddy.NotifyMeService.SmsResponse> PingmePleasebySmsAsync(FoodOrderingBuddy.NotifyMeService.SmsRequest smsRequest) {
            return base.Channel.PingmePleasebySmsAsync(smsRequest);
        }
    }
}
