//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderingBuddy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
    
        public int MenuItemId { get; set; }
        public int MenuCategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public bool Visible { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual MenuCatergory MenuCatergory { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
}
