//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderingBuddy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuCatergory
    {
        public MenuCatergory()
        {
            this.MenuItems = new HashSet<MenuItem>();
        }
    
        public int MenuCatergoryId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<MenuItem> MenuItems { get; set; }
    }
}
