//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderingBuddy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.NotifyMeServices = new HashSet<NotifyMeService>();
        }
    
        public int OrderId { get; set; }
        public string Username { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int MenuItemsTotal { get; set; }
        public decimal Total { get; set; }
        public string OrderResponse { get; set; }
        public Nullable<int> QueueId { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<NotifyMeService> NotifyMeServices { get; set; }
    }
}
